- name: SQL configuration
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql
      state: present

  - name: start mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes


